/* 网站基本信息 */
export const SITE_META = {
  NAME: `Supereasy Game`, // 网站名称
  URL: `https://www.supereasygame.com/`, // 网站主网址
  DOMAIN: `supereasygame.com`, // 网站域名
};

/* 数据获取设置 */
export const RENEW_DATA = false; // 设置为 true 强制获取最新数据

/* 统计信息 */
export const GA_ID = `UA-183890722-7`; // Google Analytics ID

/* 广告信息 / 设置 */
export const DEV_MODE = true; // 开发环境下默认设置 data-adtest="on", 测试环境设置为 true, 生产环境设置为 false

export const ADSENSE_ID = `ca-pub-9209477879340784`; // Google AdSense ID,必须与域名匹配
export const ADS_SLOT_ID = {
  HOME: `6442655892`, // 首页广告ID
  CATEGORY: `9994888098`, // 分类页(含全部游戏页)广告ID
  DETAIL: `2064427189`, // 详情页广告ID
};

/* 游戏链接参数 */
export const CHANNEL = `abgame`; // 渠道参数
export const GAME_DOMAIN = `https://cdn2.supereasygame.com`; // 游戏域名
export const GAME_PATH =
  GAME_DOMAIN + `/newgames/minigame.html?platform=` + CHANNEL + `&appid=`; // 游戏路径

/* 游戏图片参数 */
export const IMAGE_PATH = `https://cdn.iwantalipstick.com/gameicon2/`; // 图片基础域名+路径
export const IMAGE_FORMAT = `jpg`; // 图片默认格式,目前支持jpg/png/webp/avif

/* 游戏选项 */
export const SELECTED_GAMES = [
  "Knife",
  "JumpSmash",
  "CrazyMoto",
  "CrazyKart3D",
  "FireTheGun",
  "FeverRacing",
  "ColorBall3D",
  "CrazyKnife",
  "BoardTheTrain",
  "MrRacer",
  "BigSword",
  "HiTaxi",
  "TrafficRun",
  "MrBullet",
  "LetMeIn",
  "SnakeGo",
  "DessertConnect",
  "SwiftRider",
  "CrackShot",
  "CrazyGunfight",
  "GoldenGlove",
  "ColorRing",
  "PianoKeys",
  "ArchersKing",
  "MyBabyCare",
  "DartsKing3D",
  "CrazyRace",
  "BallIsComing",
  "HungyBunny",
  "TheSameWorld",
  "SuperMiner",
  "BounceShooter",
  "HillRacing",
  "BatterKing",
  "BlockGun3D",
  "ZombieSurvival",
  "FruitMonster",
  "FierceCity",
  "IronAttack",
  "AceMan",
  "AirBrawl",
  "BumbleShooter",
  "AmazingRoad",
  "RainbowSplash",
  "MagicParkour",
  "CrazyDrift",
  "FruitsFall",
  "RocketJump",
  "MagicPaint",
  "GlidingCharger",
  "RoadCharger",
  "ArcheryMaster",
  "UltraDrift",
  "SharkIsComing",
  "PuppyRun",
  "PenguinDash",
  "MonsterCrash",
  "DeathJump",
  "HungryMonster",
  "HungryAnimals",
  "JumpingMonkey",
  "MergeKill",
  "CrazyTrain3D",
  "CrazyHammer",
  "VirusWar",
  "TrappedPirate",
  "StickmanVsZombies",
  "FingerCannon",
  "BulletMan",
  "KnockBalls",
  "GunShooter",
  "MergeGuns3D",
  "BulletMaster3D",
  "CrashTower3D",
  "TowerBlast3D",
  "ShootSmash",
  "ShootingCubes",
  "BubbleBlast",
  "FlyPass",
  "KillAllZombies",
  "CollectColorfulBalls",
  "KimbapRun",
  "AnipopLink",
  "PetsMatch",
  "HappyBilliards",
  "SuperThrow",
  "CrazyBomb",
  "HelpTheZombie",
  "SaveThePets",
  "SoccerHero",
  "TableTennisChampionship",
  "MagicDonuts",
  "SolitaireClassic",
  "DeathRun",
  "IdleRestaurantTycoon",
  "ImEmpire",
  "MahjongConnect",
  "Mining",
  "MiningMaster",
  "Transform",
  "DefenseTower",
  "DragonCrush",
  "TwistyRoad",
  "ZooBlast",
  "ZumaMarbles",
  "BlockPuzzle",
  "CrazyPortal",
  "DressQueen",
  "MahjongLink3D",
  "MergeAndDefense",
  "MergeMagicJewellery",
  "PetRun",
  "SkyRunning3D",
  "SuperGolf",
  "TowerDefenseX",
  "PandaRescue",
  "FillTheGlass",
  "MagicNumber",
  "PlantBeatZombies",
  "AirHockey3D",
  "MyBowling3D",
  "Chess3D",
  "8BallKing",
  "MyUnicorn",
  "MagicJigsaw",
  "FairyTalesPuzzle",
  "PipePuzzle",
  "TrafficPassing",
  "SplittingCells",
  "FeedMaster",
  "FinalBattle",
  "FrozenMagic",
  "SuperDefense",
  "Super2048",
  "BubblePop",
  "RelivedLife",
  "CandyHit",
  "MergeCat",
  "MelodyLink",
  "PuzzleVenture",
  "BrainMaster",
  "AntRun",
  "BombingTime",
  "BlockMaze",
  "HappyTetris",
  "MagicPainter",
  "MatchingCook",
  "ColorBead",
  "ColorSplash",
  "RollingAgent",
  "RushingRover",
  "OpenFire",
  "BlockMaster",
  "PouringBall",
  "EasyCharger",
  "CopyLaser",
  "LostInLust",
  "BattleBurger",
  "GravityBowling",
  "HouseLink",
  "MagicCarpenter",
  "MyCat",
  "IslandSurvival",
  "HamsterRun",
  "SuperCells",
  "NastyBomb",
  "DashCat",
  "CrazyConveyor",
  "CleverJump",
  "BigEater",
  "CrayonPop",
  "ColorCrash",
  "BuilderRun",
  "WildRoll",
  "RoofRunner",
  "MadEraser",
  "HarvestStory",
  "CityExpress",
  "FreeFall",
  "MyHome",
  "MagicWorm",
  "HelpTheSheep",
  "RollingBall",
  "MagicDraw",
  "HelpTheFish",
  "TrainIsComing",
  "SpinTheMaze",
  "CutMaster",
  "CountingMaster",
  "CleverRescue",
  "AttackHero",
  "NoneLess",
  "CrazyJump",
  "SuperArcher",
  "FutureWarrior",
  "SuperSoccer",
  "DigEscape",
  "CleverStrut",
  "TinyWar",
  "ShootingStar",
  "ColorHammer",
  "BilliardKing",
  "FuryEdge",
  "MagicBomb",
  "BestShooter",
  "ArcheryKing",
  "RushAndFire",
  "BestSniper",
  "SnakeHit",
  "BraveArcher",
  "PowerShooter",
  "GoldenBoot",
  "SuperCoaster",
  "SausageRun",
  "MyTerritory",
  "Hurricane",
  "WoodIsland",
  "InfiDefense",
  "BoomingPlant",
  "IceEscape",
  "HumanTower",
  "SkatingMaster",
]; // 选取游戏
export const EXCLUDED_GAMES = []; // 排除游戏
export const FEATURED_GAMES = []; // 推荐游戏
export const TOP_GAMES = [
  { appid: `JumpSmash`, order: 1 },
  { appid: `BoardTheTrain`, order: 2 },
  { appid: `TrafficRun`, order: 3 },
  { appid: `LostInLust`, order: 4 },
  { appid: `MyHome`, order: 5 },
  { appid: `CrazyKnife`, order: 6 },
  { appid: `RoofRunner`, order: 7 },
  { appid: `CrazyMoto`, order: 8 },
  { appid: `PowerShooter`, order: 9 },
  { appid: `FireTheGun`, order: 10 },
  { appid: `ZombieSurvival`, order: 11 },
  { appid: `ColorBall3D`, order: 12 },
  { appid: `FeverRacing`, order: 13 },
  { appid: `SpinTheMaze`, order: 14 },
  { appid: `MrBullet`, order: 15 },
]; // 首推游戏
