import Head from "next/head";
import Script from "next/script";
import Banner from "../../components/Banner";
import GameList from "../../components/GameList";
import Layout from "../../components/Layout";
import { getData } from "../../lib/api";
import { SITE_META, ADS_SLOT_ID, ADSENSE_ID } from "../../lib/constants";

export default function Category({ data }) {
  // console.log(`data: `, data);
  return (
    <>
      <Head>
        <title>{SITE_META.NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        id={`gads-init`}
        async
        src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${ADSENSE_ID}`}
        crossOrigin="anonymous"
      />
      <Layout navItems={data.categories}>
        <div className="category container mx-auto">
          <Banner slot={ADS_SLOT_ID.CATEGORY} auto />
          <header className="page-title">
            <h1
              dangerouslySetInnerHTML={{
                __html: `${data.games[0].category} Games`,
              }}
            />
            <span>{`Total: ${data.games.length}`}</span>
          </header>
          <GameList items={data.games} />
        </div>
      </Layout>
    </>
  );
}

export const getStaticProps = async (ctx) => {
  const games = await getData(`games`);
  function toSlug(cat) {
    return cat.toLowerCase().replace(/\./, ``).replace(/ /g, `-`);
  }
  let filteredGames = games.filter(
    (game) => toSlug(game.category) === ctx.params.slug
  );
  const categories = await getData("category");

  return {
    props: {
      data: {
        games: filteredGames,
        categories,
      },
    },
  };
};

export const getStaticPaths = async () => {
  const categories = await getData(`category`);

  return {
    paths: categories.map((i) => ({
      params: { slug: i.toLowerCase().replace(/\./, ``).replace(/ /g, `-`) },
    })),
    fallback: false,
  };
};
