import Head from "next/head";
import Banner from "../components/Banner";
import GameList from "../components/GameList";
import Layout from "../components/Layout";
import { getData } from "../lib/api";
import { SITE_META, ADS_SLOT_ID } from "../lib/constants";

export default function Home({ data }) {
  console.log(`data: `, data.games.length);
  return (
    <>
      <Head>
        <title>{SITE_META.NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout navItems={data.categories}>
        <div className="home container mx-auto">
          <Banner slot={ADS_SLOT_ID.HOME} />
          <GameList items={data.games} />
        </div>
      </Layout>
    </>
  );
}

export const getStaticProps = async (ctx) => {
  const games = await getData(`games`);
  const categories = await getData("category");

  return {
    props: {
      data: {
        games,
        categories,
      },
    },
  };
};
